/**
 * @fileoverview Configuration globale de l'application
 * @module config
 */

// Configuration VAD (Voice Activity Detection)
export const VAD_CONFIG = {
  VOLUME_THRESHOLD: 0.015,     // Seuil de détection de voix
  SILENCE_DURATION: 1000,      // Durée de silence pour arrêter (ms)
  MIN_RECORDING_DURATION: 600, // Durée minimale d'enregistrement (ms)
  RECORDING_INTERVAL: 80       // Intervalle d'analyse (ms)
};

// Configuration des notifications
export const NOTIFICATION_CONFIG = {
  enabled: true,
  sound: true,
  desktop: true,
  toastDuration: 4000
};

// Configuration des langues supportées
export const LANGUAGES = {
  fr: { name: 'Français', flag: '🇫🇷', nativeName: 'Français', code: 'fr', voice: 'onyx' },
  en: { name: 'English', flag: '🇬🇧', nativeName: 'English', code: 'en', voice: 'alloy' },
  zh: { name: '中文', flag: '🇨🇳', nativeName: '中文', code: 'zh', voice: 'nova' },
  de: { name: 'Deutsch', flag: '🇩🇪', nativeName: 'Deutsch', code: 'de', voice: 'onyx' },
  es: { name: 'Español', flag: '🇪🇸', nativeName: 'Español', code: 'es', voice: 'onyx' },
  it: { name: 'Italiano', flag: '🇮🇹', nativeName: 'Italiano', code: 'it', voice: 'alloy' },
  pt: { name: 'Português', flag: '🇵🇹', nativeName: 'Português', code: 'pt', voice: 'shimmer' }
};

// Traductions de l'interface
export const UI_TRANSLATIONS = {
  fr: {
    title: 'RealTranslate',
    subtitle: 'Choisissez vos langues de traduction',
    yourLanguage: '📱 Votre langue',
    targetLanguage: '🗣️ Langue à traduire',
    startButton: 'Commencer la traduction',
    friends: 'Amis',
    groups: 'Groupes',
    profile: 'Profil',
    logout: 'Déconnexion',
    friendsTitle: '👥 Amis',
    searchUsers: '🔍 Rechercher des utilisateurs',
    searchPlaceholder: 'Nom d\'affichage exact',
    searchButton: 'Rechercher',
    friendRequests: '📥 Demandes d\'ami reçues',
    myFriends: '✅ Mes amis',
    noRequests: 'Aucune demande d\'ami en attente',
    noPendingRequests: 'Aucune demande d\'ami en attente',
    noFriends: 'Aucun ami pour le moment. Recherchez des utilisateurs ci-dessus!',
    accept: 'Accepter',
    reject: 'Refuser',
    remove: 'Retirer',
    addFriend: 'Ajouter',
    minTwoChars: 'Entrez au moins 2 caractères',
    noUserFound: 'Aucun utilisateur trouvé avec ce nom',
    searchError: 'Erreur lors de la recherche',
    groupsTitle: '💬 Groupes de discussion',
    createGroup: '➕ Créer un groupe',
    myGroups: '📋 Mes groupes',
    groupName: 'Nom du groupe',
    selectFriends: 'Sélectionner des amis à ajouter:',
    createButton: 'Créer le groupe',
    noGroups: 'Aucun groupe. Créez-en un ci-dessus!',
    noFriendsAddInTab: 'Vous n\'avez pas encore d\'amis. Ajoutez-en dans l\'onglet Amis!',
    members: 'membres',
    createdOn: 'Créé le',
    chatTitle: '💬',
    details: '⚙️ Détails',
    close: '✕ Fermer',
    typeMessage: 'Tapez votre message...',
    send: 'Envoyer',
    noMessages: 'Aucun message pour le moment. Soyez le premier à écrire!',
    listen: 'Écouter',
    copy: 'Copier',
    audioPlaybackError: 'Erreur lors de la lecture audio',
    copyError: 'Erreur lors de la copie',
    profileTitle: '⚙️ Mon Profil',
    accountInfo: '👤 Informations du compte',
    email: 'Email:',
    displayName: 'Nom d\'affichage:',
    subscription: 'Abonnement:',
    updateDisplayName: '✏️ Modifier le nom d\'affichage',
    newDisplayName: 'Nouveau nom d\'affichage',
    update: 'Mettre à jour',
    'pricing-subtitle': 'Choisissez le plan adapté à vos besoins',
    'pricing-free-title': 'GRATUIT',
    'pricing-per-month': '/mois',
    'pricing-popular': 'POPULAIRE',
    'pricing-transcriptions': 'transcriptions',
    'pricing-translations': 'traductions',
    'pricing-tts': 'synthèses vocales',
    'pricing-7-languages': '7 langues disponibles',
    'pricing-priority-support': 'Support prioritaire',
    'pricing-dedicated-support': 'Support dédié 24/7',
    'pricing-api-access': 'Accès API',
    'pricing-subscribe': 'S\'abonner'
  },
  en: {
    title: 'RealTranslate',
    subtitle: 'Choose your translation languages',
    yourLanguage: '📱 Your language',
    targetLanguage: '🗣️ Language to translate',
    startButton: 'Start translation',
    friends: 'Friends',
    groups: 'Groups',
    profile: 'Profile',
    logout: 'Logout',
    friendsTitle: '👥 Friends',
    searchUsers: '🔍 Search users',
    searchPlaceholder: 'Exact display name',
    searchButton: 'Search',
    friendRequests: '📥 Friend requests',
    myFriends: '✅ My friends',
    noRequests: 'No pending friend requests',
    noPendingRequests: 'No pending friend requests',
    noFriends: 'No friends yet. Search for users above!',
    accept: 'Accept',
    reject: 'Reject',
    remove: 'Remove',
    addFriend: 'Add',
    minTwoChars: 'Enter at least 2 characters',
    noUserFound: 'No user found with that name',
    searchError: 'Error during search',
    groupsTitle: '💬 Discussion groups',
    createGroup: '➕ Create group',
    myGroups: '📋 My groups',
    groupName: 'Group name',
    selectFriends: 'Select friends to add:',
    createButton: 'Create group',
    noGroups: 'No groups. Create one above!',
    noFriendsAddInTab: 'You don\'t have any friends yet. Add some in the Friends tab!',
    members: 'members',
    createdOn: 'Created on',
    chatTitle: '💬',
    details: '⚙️ Details',
    close: '✕ Close',
    typeMessage: 'Type your message...',
    send: 'Send',
    noMessages: 'No messages yet. Be the first to write!',
    listen: 'Listen',
    copy: 'Copy',
    audioPlaybackError: 'Error playing audio',
    copyError: 'Error copying',
    profileTitle: '⚙️ My Profile',
    accountInfo: '👤 Account information',
    email: 'Email:',
    displayName: 'Display name:',
    subscription: 'Subscription:',
    updateDisplayName: '✏️ Change display name',
    newDisplayName: 'New display name',
    update: 'Update',
    'pricing-subtitle': 'Choose the plan that fits your needs',
    'pricing-free-title': 'FREE',
    'pricing-per-month': '/month',
    'pricing-popular': 'POPULAR',
    'pricing-transcriptions': 'transcriptions',
    'pricing-translations': 'translations',
    'pricing-tts': 'text-to-speech',
    'pricing-7-languages': '7 languages available',
    'pricing-priority-support': 'Priority support',
    'pricing-dedicated-support': 'Dedicated 24/7 support',
    'pricing-api-access': 'API access',
    'pricing-subscribe': 'Subscribe'
  },
  zh: {
    title: 'RealTranslate',
    subtitle: '选择您的翻译语言',
    yourLanguage: '📱 您的语言',
    targetLanguage: '🗣️ 目标语言',
    startButton: '开始翻译',
    friends: '好友',
    groups: '群组',
    profile: '个人资料',
    logout: '退出',
    friendsTitle: '👥 好友',
    noFriends: '还没有好友。在上方搜索用户！',
    accept: '接受',
    reject: '拒绝',
    remove: '移除',
    addFriend: '添加',
    noMessages: '还没有消息。成为第一个发言的人！',
    listen: '播放',
    copy: '复制',
    send: 'Envoyer'
  },
  de: {
    title: 'RealTranslate',
    subtitle: 'Wählen Sie Ihre Übersetzungssprachen',
    yourLanguage: '📱 Ihre Sprache',
    targetLanguage: '🗣️ Zielsprache',
    startButton: 'Übersetzung starten',
    friends: 'Freunde',
    groups: 'Gruppen',
    profile: 'Profil',
    logout: 'Abmelden',
    noMessages: 'Noch keine Nachrichten. Sei der Erste!',
    listen: 'Anhören',
    copy: 'Kopieren',
    send: 'Senden'
  },
  es: {
    title: 'RealTranslate',
    subtitle: 'Elige tus idiomas de traducción',
    yourLanguage: '📱 Tu idioma',
    targetLanguage: '🗣️ Idioma a traducir',
    startButton: 'Comenzar traducción',
    friends: 'Amigos',
    groups: 'Grupos',
    profile: 'Perfil',
    logout: 'Cerrar sesión',
    noMessages: 'Aún no hay mensajes. ¡Sé el primero!',
    listen: 'Escuchar',
    copy: 'Copiar',
    send: 'Enviar'
  },
  it: {
    title: 'RealTranslate',
    subtitle: 'Scegli le tue lingue di traduzione',
    yourLanguage: '📱 La tua lingua',
    targetLanguage: '🗣️ Lingua da tradurre',
    startButton: 'Inizia la traduzione',
    friends: 'Amici',
    groups: 'Gruppi',
    profile: 'Profilo',
    logout: 'Esci',
    noMessages: 'Nessun messaggio. Sii il primo!',
    listen: 'Ascolta',
    copy: 'Copia',
    send: 'Invia'
  },
  pt: {
    title: 'RealTranslate',
    subtitle: 'Escolha seus idiomas de tradução',
    yourLanguage: '📱 Seu idioma',
    targetLanguage: '🗣️ Idioma para traduzir',
    startButton: 'Iniciar tradução',
    friends: 'Amigos',
    groups: 'Grupos',
    profile: 'Perfil',
    logout: 'Sair',
    noMessages: 'Sem mensagens. Seja o primeiro!',
    listen: 'Ouvir',
    copy: 'Copiar',
    send: 'Enviar'
  }
};

// Emojis de réaction disponibles
export const REACTION_EMOJIS = ['👍', '❤️', '😂', '😮', '😢', '😡'];

export default {
  VAD_CONFIG,
  NOTIFICATION_CONFIG,
  LANGUAGES,
  UI_TRANSLATIONS,
  REACTION_EMOJIS
};
